project_name: terraform-lsp
release:
  github:
    owner: juliosueiras
    name: terraform-lsp
  name_template: '{{.Tag}}'
scoop:
  name: terraform-lsp
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  url_template: https://github.com/juliosueiras/terraform-lsp/releases/download/{{
    .Tag }}/{{ .ArtifactName }}
env:
  - GO111MODULE=on
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  targets:
  - linux_amd64
  - darwin_amd64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X main.Version={{.Version}} -X main.GitCommit={{.FullCommit}} -X main.Date={{.Date}}
  binary: terraform-lsp
  lang: go
  flags:
  - -mod=vendor
archives:
  - id: terraform-lsp
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
      }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com
