jobs:
  include:
    - language: nix
      nix: 2.3.5
      os: linux
      env: TRAVIS_OS=linux
    - language: nix
      nix: 2.3.5
      os: osx
      env: TRAVIS_OS=osx
    - stage: GoReleaser Deployment
      services:
        - docker
      language: go
      go:
      - 1.14
      #if: tag IS present
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux

after_script:
  - file ./result/bin/terraform-lsp
